title: "Shalin Anand Jain"
author: "Shalin Anand Jain"
repository: shalin-jain/shalin-jain.github.io
# email: "you@example.com"
# description: "PhD student in robotics and RL."
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
